export default {
  INITIAL_LOAD: 'INITIAL_LOAD',
  INITIAL_LOAD_COMPLETED: 'INITIAL_LOAD_COMPLETED',
  ADD_CITY_TO_STORE: 'ADD_CITY_TO_STORE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',
  FILTER_FAVORITES: 'FILTER_FAVORITES',
  SET_DETAIL_CITY: 'SET_DETAIL_CITY',
  SET_CURRENT_LOCATION_DETAIL_CITY: 'SET_CURRENT_LOCATION_DETAIL_CITY',
  LOAD_DETAIL_CITY: 'LOAD_DETAIL_CITY',
  LOAD_DETAIL_CITY_ERROR: 'LOAD_DETAIL_CITY_ERROR',
  REMOVE_CITY_FROM_LIST: 'REMOVE_CITY_FROM_LIST',
  ADD_REMOVE_FAVORITE_CITY: 'ADD_REMOVE_FAVORITE_CITY',
};
